### ISSUE TITLE
A bit of unification in `.catalog.category.updateCategory`

### ISSUE THREAD

**Issue by siarheidudko** [kzhang-dsg/bigcommerce-api-client#10]
When we call a product update, we pass the identifier as the first argument, and the data as the second. (this happens in most cases, because the identifier is part of the URL).
When we update the category, we pass one argument that already contains the identifier (readonly in the API).

**Comment by siarheidudko** [comment]
For more info see https://github.com/kzhang-dsg/bigcommerce-api-client/pull/11

**Comment by kzhang-dsg** [comment]
Thanks! code merged.
