### ISSUE TITLE
Suggestion: retryDelay strategy

### ISSUE THREAD

**Issue by sdudko-2** [kzhang-dsg/bigcommerce-api-client#12]
Since the bigcommerce API often returns error 429 and in general services have a feature of being unavailable for some time, the usual behavior of `retryDelay` is insufficient to automatically fix this problem.
It seems to me the best strategy is to behave with increasing delay.
```ts
retryDelay = 5000
nextRetry = attempt * retryDelay
/*
1 - 5s
2 - + 10s
3 - + 15s
...
*/
```
In addition, you can add some random variable, this helps to bypass the locks at the firewall level, which does not like requests without time spread and considers them a DoS attack.

```ts
const {
  randomInt,
} = await import('node:crypto')

retryDelay = 5000
nextRetry = attempt * retryDelay + randomInt(0, retryDelay)
/*
1 - 5s + [0..5]?s
2 - + 10s + [0..5]?s
3 - + 15s + [0..5]?s
...
*/
```

**Comment by sdudko-2** [comment]
Alternatively, you can add the `retryStrategy` parameter and allow the user to override it independently.
With default behavior:
```ts
retryStrategy = (attempt: number, retryDelay: number): number => retryDelay
```

**Comment by kzhang-dsg** [comment]
That is a good idea. Before v0.7.2, the relay strategy is like this:
1.  nextRetry = attempt * retryDelay
2. If  API returns error 429, then nextRetry = value in "X-Rate-Limit-Time-Reset-Ms" header

In v0.7.2, the relay strategy is changed to:
1.  nextRetry = attempt * retryDelay +  randomInt(0, retryDelay)
2. If  API returns error 429, then nextRetry = value in "X-Rate-Limit-Time-Reset-Ms" header
