### ISSUE TITLE
Error when adding a product to the channel (store).

### ISSUE THREAD

**Issue by siarheidudko** [kzhang-dsg/bigcommerce-api-client#13]
Error: Failed to call BigCommerce API https:://api.bigcommerce.com/stores/...../v3/catalog/products/channel-assignments. Response Status: 405, Response: {"status":405,"title":"Method Not Allowed","type":"https://developer.bigcommerce.com/api-docs/getting-started/api-status-codes","detail":"The requested HTTP method is invalid for this endpoint."}. Retries: 0. Error: Request failed with status code 405.

I will add a fix today.

**Comment by siarheidudko** [comment]
https://github.com/kzhang-dsg/bigcommerce-api-client/pull/14

**Comment by kzhang-dsg** [comment]
Thanks. Code merged.
