### ISSUE TITLE
Create Products Category Assignments using wrong HTTP Method

### ISSUE THREAD

**Issue by AndrewBarber** [kzhang-dsg/bigcommerce-api-client#18]
It looks like `createCategoryAssignments` is using POST instead of PUT as specified within the [BC Docs](https://developer.bigcommerce.com/docs/rest-catalog/products/category-assignments#create-products-category-assignments).

Opening a PR to change the HTTP method...

**Comment by kzhang-dsg** [comment]
Thanks. Fixed in https://github.com/kzhang-dsg/bigcommerce-api-client/releases/tag/0.7.12
