### ISSUE TITLE
Unable to use Cart Metafields

### ISSUE THREAD

**Issue by harwoodspike** [kzhang-dsg/bigcommerce-api-client#20]
I am trying to use carts metafields api.

```
      await bigCommerce.carts.metafields.createMetafield(cart.id, {
        permission_set: 'read',
        namespace: 'namespace',
        key: 'key',
        value: 'value',
      })
```

But I am getting `Failed to call BigCommerce API POST https:://api.bigcommerce.com/stores/{storehash}/v3/catalog/carts/{cartid}/metafields. Response Status: 404, Response: {\"status\":404,\"title\":\"Not Found\",\"type\":\"https://developer.bigcommerce.com/api-docs/getting-started/api-status-codes\"}. Retries: 0. Error: Request failed with status code 404.`

When I was comparing the BigCommerce docs with the sdk code I saw that the urls are different.

You guys are using `/v3/catalog/carts/<cartid>/metafields` but the docs at https://developer.bigcommerce.com/docs/rest-management/carts/metafields say the url is `/v3/carts/{cart_id}/metafields`

Is the url you guys are using wrong or am I using the wrong api?

I am setting up a headless store and I am just trying to add metadata to the cart before sending the customer to checkout.

**Comment by kzhang-dsg** [comment]
Fixed in 0.7.19
