### ISSUE TITLE
Type `product_Put_Collection` does not contain IDs to update

### ISSUE THREAD

**Issue by siarheidudko** [kzhang-dsg/bigcommerce-api-client#6]
Type `product_Put_Collection` does not contain IDs to update.
[See PR#5](https://github.com/kzhang-dsg/bigcommerce-api-client/pull/5)

**Comment by kzhang-dsg** [comment]
Thanks! Following your instruction I fixed it in the upstream https://github.com/kzhang-dsg/bigcommerce-api-specs repo and created a PR https://github.com/bigcommerce/api-specs/pull/1249 to BigCommerce API Spec.

Fixed in 0.6.2
