### ISSUE TITLE
A bit of unification in `.catalog.products.updateBrand`

### ISSUE THREAD

**Issue by siarheidudko** [kzhang-dsg/bigcommerce-api-client#8]
When we call a product update, we pass the identifier as the first argument, and the data as the second. (this happens in most cases, because the identifier is part of the URL).
When we update the brand, we pass one argument that already contains the identifier (readonly in the API).

**Comment by siarheidudko** [comment]
For more info see [#9](https://github.com/kzhang-dsg/bigcommerce-api-client/pull/9)

**Comment by kzhang-dsg** [comment]
Thanks. Will update the API specs and include it in the next release
